-- ReplicatedStorage/Configuration/ControlsConfig.luau
-- Input action names for ContextActionService
-- See https://developer.roblox.com/en-us/api-reference/class/ContextActionService
local ControlsConfig = {
    ThrottleAction   = "VehicleThrottle",
    SteerLeftAction  = "VehicleSteerLeft",
    SteerRightAction = "VehicleSteerRight",
    BrakeAction      = "VehicleBrake",
    FireAction       = "VehicleFire",
}
return ControlsConfig
